apiVersion: apps/v1
kind: Deployment
metadata:
  name: l7bench-server-deployment
  labels:
    app: l7bench-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: l7bench-server
  template:
    metadata:
      labels:
        app: l7bench-server
    spec:
      containers:
      - name: l7bench-server
        image: camelinx/l7bench-server:1.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: nginx-certs
          mountPath: /etc/nginx-certs
        - name: nginx-conf
          mountPath: /usr/local/openresty/nginx/conf/conf.d
        ports:
        - containerPort: 80
        - containerPort: 443
      volumes:
      - name: nginx-certs
        secret:
          secretName: nginx-default-secret
          items:
          - key: tls.crt
            path: server.crt
            mode: 400
          - key: tls.key
            path: server.key
            mode: 400
      - name: nginx-conf
        configMap:
          name: return-requested-size
          items:
          - key: nginx-conf
            path: sample.conf
---

apiVersion: v1
kind: Service
metadata:
  name: l7bench-server-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: l7bench-server
